name: amazon_wiki_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
